[project]
name = "ai-podcast"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gradio-client>=1.10.2",
    "httpx>=0.28.1",
    "newsapi>=0.1.1",
    "newsapi-python>=0.2.7",
    "pydantic>=2.11.5",
    "pydantic-settings>=2.9.1",
]
